sudo: required

language: c

services:
  - docker

before_install:
  - docker pull micchon/baccaml

script:
  - docker run -u root -v $(pwd):/tmp --rm -it micchon/baccaml sh -c 'jbuilder build && jbuilder runtest'
