sudo: required

services:
  - docker

language: c

env:
  - CONTAINER_NAME=min-caml-debug

script:
  - docker build -t micchon/min-caml:latest .
  - docker run --name ${CONTAINER_NAME} -dit micchon/min-caml:latest
  - docker ps -a
  - docker exec -it ${CONTAINER_NAME} ./runtest.sh
  - docker rm -f `docker ps -aq`
