sudo: required

language: c

services:
  - docker

before_install:
  - docker pull micchon/baccaml:0.1

script:
  - docker run -v $(pwd):/tmp --rm -it micchon/baccaml:0.1 jbuilder clean && jbuilder runtest
