sudo: required

language: c

services:
  - docker

before_install:
  - docker pull micchon/baccaml:latest

script:
  - docker run -u root -v $(pwd):/tmp --rm -it micchon/baccaml:0.1 /home/opam/.opam/4.05.0/bin/jbuilder runtest
