language: c
env:
  - OCAML_VERSION=4.07.1+32bit
cache:
  directories:
    - ${HOME}/.opam
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-multilib
  - wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.2/opam-2.0.2-x86_64-linux
  - chmod +x ${HOME}/opam
  - export PATH=${HOME}:${PATH}
  - export OPAMYES=1
  - export OPAMJOBS=2
  - opam init --compiler=${OCAML_VERSION} --disable-sandboxing
  - eval `opam config env`
  - export OPAMVERBOSE=1
install:
  - opam update --upgrade
  - opam install -y dune oUnit ppx_deriving
script:
  - dune runtest -f test/jit
  - dune runtest -f test/bytecomp
